---@class Pantsbox
---@field config PantsboxConfig
---@field palette PantsboxPalette
local Pantsbox = {}

---@alias Contrast "hard" | "soft" | ""

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class PantsboxConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field contrast Contrast?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Pantsbox.config = {
    terminal_colors = true,
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
        strings = false,
        emphasis = false,
        comments = false,
        operators = false,
        folds = false,
    },
    strikethrough = true,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    invert_intend_guides = false,
    inverse = true,
    contrast = "",
    palette_overrides = {},
    overrides = {},
    dim_inactive = false,
    transparent_mode = false,
}

-- main pantsbox color palette
---@class PantsboxPalette
Pantsbox.palette = {
    dark0_hard = "#121212",
    -- dark0_hard = "#0E1018",
    dark0 = "#282828",
    dark0_soft = "#32302f",
    dark1 = "#3c3836",
    dark2 = "#504945",
    dark3 = "#665c54",
    dark4 = "#7c6f64",
    light0_hard = "#ffffd7",
    -- light0_hard = "#f9f5d7",
    light0 = "#fbf1c7",
    light0_soft = "#f2e5bc",
    light1 = "#ebdbb2",
    light2 = "#d5c4a1",
    light3 = "#bdae93",
    light4 = "#a89984",
    bright_red = "#ff5f5f",
    bright_green = "#afaf00",
    bright_yellow = "#ffaf00",
    bright_blue = "#87af87",
    bright_purple = "#d787af",
    bright_aqua = "#87af87",
    bright_orange = "#ff8700",
    -- original colors
    -- TODO: Make these colors an option
    -- bright_red = "#fb4934",
    -- bright_green = "#b8bb26",
    -- bright_yellow = "#fabd2f",
    -- bright_blue = "#83a598",
    -- bright_purple = "#d3869b",
    -- bright_aqua = "#8ec07c",
    -- bright_orange = "#fe8019",
    neutral_red = "#cc241d",
    neutral_green = "#98971a",
    neutral_yellow = "#d79921",
    neutral_blue = "#458588",
    neutral_purple = "#b16286",
    neutral_aqua = "#689d6a",
    neutral_orange = "#d65d0e",
    faded_red = "#9d0006",
    faded_green = "#79740e",
    faded_yellow = "#b57614",
    faded_blue = "#076678",
    faded_purple = "#8f3f71",
    faded_aqua = "#427b58",
    faded_orange = "#af3a03",
    dark_red_hard = "#792329",
    dark_red = "#722529",
    dark_red_soft = "#7b2c2f",
    light_red_hard = "#fc9690",
    light_red = "#fc9487",
    light_red_soft = "#f78b7f",
    dark_green_hard = "#5a633a",
    dark_green = "#62693e",
    dark_green_soft = "#686d43",
    light_green_hard = "#d3d6a5",
    light_green = "#d5d39b",
    light_green_soft = "#cecb94",
    dark_aqua_hard = "#3e4934",
    dark_aqua = "#49503b",
    dark_aqua_soft = "#525742",
    light_aqua_hard = "#e6e9c1",
    light_aqua = "#e8e5b5",
    light_aqua_soft = "#e1dbac",
    gray = "#928374",
}

-- get a hex list of pantsbox colors based on current bg and constrast config
local function get_colors()
    local p = Pantsbox.palette
    local config = Pantsbox.config

    for color, hex in pairs(config.palette_overrides) do
        p[color] = hex
    end

    local bg = vim.o.background
    local contrast = config.contrast

    local color_groups = {
        dark = {
            bg0 = p.dark0,
            bg1 = p.dark1,
            bg2 = p.dark2,
            bg3 = p.dark3,
            bg4 = p.dark4,
            fg0 = p.light0,
            fg1 = p.light1,
            fg2 = p.light2,
            fg3 = p.light3,
            fg4 = p.light4,
            red = p.bright_red,
            green = p.bright_green,
            yellow = p.bright_yellow,
            blue = p.bright_blue,
            purple = p.bright_purple,
            aqua = p.bright_aqua,
            orange = p.bright_orange,
            neutral_red = p.neutral_red,
            neutral_green = p.neutral_green,
            neutral_yellow = p.neutral_yellow,
            neutral_blue = p.neutral_blue,
            neutral_purple = p.neutral_purple,
            neutral_aqua = p.neutral_aqua,
            dark_red = p.dark_red,
            dark_green = p.dark_green,
            dark_aqua = p.dark_aqua,
            gray = p.gray,
        },
        light = {
            bg0 = p.light0,
            bg1 = p.light1,
            bg2 = p.light2,
            bg3 = p.light3,
            bg4 = p.light4,
            fg0 = p.dark0,
            fg1 = p.dark1,
            fg2 = p.dark2,
            fg3 = p.dark3,
            fg4 = p.dark4,
            red = p.faded_red,
            green = p.faded_green,
            yellow = p.faded_yellow,
            blue = p.faded_blue,
            purple = p.faded_purple,
            aqua = p.faded_aqua,
            orange = p.faded_orange,
            neutral_red = p.neutral_red,
            neutral_green = p.neutral_green,
            neutral_yellow = p.neutral_yellow,
            neutral_blue = p.neutral_blue,
            neutral_purple = p.neutral_purple,
            neutral_aqua = p.neutral_aqua,
            dark_red = p.light_red,
            dark_green = p.light_green,
            dark_aqua = p.light_aqua,
            gray = p.gray,
        },
    }

    if contrast ~= nil and contrast ~= "" then
        color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
        color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
        color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
        color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
    end

    return color_groups[bg]
end

local function get_groups()
    local colors = get_colors()
    local config = Pantsbox.config

    if config.terminal_colors then
        local term_colors = {
            colors.bg0,
            colors.neutral_red,
            colors.neutral_green,
            colors.neutral_yellow,
            colors.neutral_blue,
            colors.neutral_purple,
            colors.neutral_aqua,
            colors.fg4,
            colors.gray,
            colors.red,
            colors.green,
            colors.yellow,
            colors.blue,
            colors.purple,
            colors.aqua,
            colors.fg1,
        }
        for index, value in ipairs(term_colors) do
            vim.g["terminal_color_" .. index - 1] = value
        end
    end

    local groups = {
        PantsboxFg0 = { fg = colors.fg0 },
        PantsboxFg1 = { fg = colors.fg1 },
        PantsboxFg2 = { fg = colors.fg2 },
        PantsboxFg3 = { fg = colors.fg3 },
        PantsboxFg4 = { fg = colors.fg4 },
        PantsboxGray = { fg = colors.gray },
        PantsboxBg0 = { fg = colors.bg0 },
        PantsboxBg1 = { fg = colors.bg1 },
        PantsboxBg2 = { fg = colors.bg2 },
        PantsboxBg3 = { fg = colors.bg3 },
        PantsboxBg4 = { fg = colors.bg4 },
        PantsboxRed = { fg = colors.red },
        PantsboxRedBold = { fg = colors.red, bold = config.bold },
        PantsboxGreen = { fg = colors.green },
        PantsboxGreenBold = { fg = colors.green, bold = config.bold },
        PantsboxYellow = { fg = colors.yellow },
        PantsboxYellowBold = { fg = colors.yellow, bold = config.bold },
        PantsboxBlue = { fg = colors.blue },
        PantsboxBlueBold = { fg = colors.blue, bold = config.bold },
        PantsboxPurple = { fg = colors.purple },
        PantsboxPurpleBold = { fg = colors.purple, bold = config.bold },
        PantsboxAqua = { fg = colors.aqua },
        PantsboxAquaBold = { fg = colors.aqua, bold = config.bold },
        PantsboxOrange = { fg = colors.orange },
        PantsboxOrangeBold = { fg = colors.orange, bold = config.bold },
        PantsboxRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
            or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
            or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
            or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
            or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
            or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
            or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
            or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
        PantsboxRedUnderline = { undercurl = config.undercurl, sp = colors.red },
        PantsboxGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
        PantsboxYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
        PantsboxBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
        PantsboxPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
        PantsboxAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
        PantsboxOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
        Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
        NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
        NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
        CursorLine = { bg = colors.bg1 },
        CursorColumn = { link = "CursorLine" },
        TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
        TabLine = { link = "TabLineFill" },
        MatchParen = { bg = colors.bg3, bold = config.bold },
        ColorColumn = { bg = colors.bg1 },
        Conceal = { fg = colors.blue },
        CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
        NonText = { link = "PantsboxBg2" },
        SpecialKey = { link = "PantsboxFg4" },
        Visual = { bg = colors.bg3, reverse = config.invert_selection },
        VisualNOS = { link = "Visual" },
        Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
        IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { link = "PantsboxPurple" },
        Underlined = { fg = colors.blue, underline = config.underline },
        StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
        StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
        WinBar = { fg = colors.fg4, bg = colors.bg0 },
        WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
        WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
        WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
        Directory = { link = "PantsboxBlueBold" },
        Title = { link = "PantsboxGreenBold" },
        ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MoreMsg = { link = "PantsboxYellowBold" },
        ModeMsg = { link = "PantsboxYellowBold" },
        Question = { link = "PantsboxOrangeBold" },
        WarningMsg = { link = "PantsboxRedBold" },
        LineNr = { fg = colors.bg4 },
        SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg },
        Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
        FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
        Cursor = { reverse = config.inverse },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { link = "PantsboxOrange" },
        Comment = { fg = colors.gray, italic = config.italic.comments },
        Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
        Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
        Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
        Statement = { link = "PantsboxRed" },
        Conditional = { link = "PantsboxRed" },
        Repeat = { link = "PantsboxRed" },
        Label = { link = "PantsboxRed" },
        Exception = { link = "PantsboxRed" },
        Operator = { fg = colors.orange, italic = config.italic.operators },
        Keyword = { link = "PantsboxRed" },
        Identifier = { link = "PantsboxBlue" },
        Function = { link = "PantsboxGreenBold" },
        PreProc = { link = "PantsboxAqua" },
        Include = { link = "PantsboxAqua" },
        Define = { link = "PantsboxAqua" },
        Macro = { link = "PantsboxAqua" },
        PreCondit = { link = "PantsboxAqua" },
        Constant = { link = "PantsboxPurple" },
        Character = { link = "PantsboxPurple" },
        String = { fg = colors.green, italic = config.italic.strings },
        Boolean = { link = "PantsboxPurple" },
        Number = { link = "PantsboxPurple" },
        Float = { link = "PantsboxPurple" },
        Type = { link = "PantsboxYellow" },
        StorageClass = { link = "PantsboxOrange" },
        Structure = { link = "PantsboxAqua" },
        Typedef = { link = "PantsboxYellow" },
        Pmenu = { fg = colors.fg1, bg = colors.bg2 },
        PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
        PmenuSbar = { bg = colors.bg2 },
        PmenuThumb = { bg = colors.bg4 },
        DiffDelete = { bg = colors.dark_red },
        DiffAdd = { bg = colors.dark_green },
        DiffChange = { bg = colors.dark_aqua },
        DiffText = { bg = colors.yellow, fg = colors.bg0 },
        SpellCap = { link = "PantsboxBlueUnderline" },
        SpellBad = { link = "PantsboxRedUnderline" },
        SpellLocal = { link = "PantsboxAquaUnderline" },
        SpellRare = { link = "PantsboxPurpleUnderline" },
        Whitespace = { fg = colors.bg2 },
        DiagnosticError = { link = "PantsboxRed" },
        DiagnosticSignError = { link = "PantsboxRedSign" },
        DiagnosticUnderlineError = { link = "PantsboxRedUnderline" },
        DiagnosticWarn = { link = "PantsboxYellow" },
        DiagnosticSignWarn = { link = "PantsboxYellowSign" },
        DiagnosticUnderlineWarn = { link = "PantsboxYellowUnderline" },
        DiagnosticInfo = { link = "PantsboxBlue" },
        DiagnosticSignInfo = { link = "PantsboxBlueSign" },
        DiagnosticUnderlineInfo = { link = "PantsboxBlueUnderline" },
        DiagnosticHint = { link = "PantsboxAqua" },
        DiagnosticSignHint = { link = "PantsboxAquaSign" },
        DiagnosticUnderlineHint = { link = "PantsboxAquaUnderline" },
        DiagnosticFloatingError = { link = "PantsboxRed" },
        DiagnosticFloatingWarn = { link = "PantsboxOrange" },
        DiagnosticFloatingInfo = { link = "PantsboxBlue" },
        DiagnosticFloatingHint = { link = "PantsboxAqua" },
        DiagnosticVirtualTextError = { link = "PantsboxRed" },
        DiagnosticVirtualTextWarn = { link = "PantsboxYellow" },
        DiagnosticVirtualTextInfo = { link = "PantsboxBlue" },
        DiagnosticVirtualTextHint = { link = "PantsboxAqua" },
        DiagnosticOk = { link = "PantsboxGreenSign" },
        LspReferenceRead = { link = "PantsboxYellowBold" },
        LspReferenceText = { link = "PantsboxYellowBold" },
        LspReferenceWrite = { link = "PantsboxOrangeBold" },
        LspCodeLens = { link = "PantsboxGray" },
        LspSignatureActiveParameter = { link = "Search" },
        gitcommitSelectedFile = { link = "PantsboxGreen" },
        gitcommitDiscardedFile = { link = "PantsboxRed" },
        GitSignsAdd = { link = "PantsboxGreen" },
        GitSignsChange = { link = "PantsboxAqua" },
        GitSignsDelete = { link = "PantsboxRed" },
        NvimTreeSymlink = { fg = colors.neutral_aqua },
        NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
        NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
        NvimTreeFileIcon = { fg = colors.light2 },
        NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
        NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
        NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = colors.neutral_purple },
        NvimTreeIndentMarker = { fg = colors.dark3 },
        NvimTreeGitDirty = { fg = colors.neutral_yellow },
        NvimTreeGitStaged = { fg = colors.neutral_yellow },
        NvimTreeGitMerge = { fg = colors.neutral_purple },
        NvimTreeGitRenamed = { fg = colors.neutral_purple },
        NvimTreeGitNew = { fg = colors.neutral_yellow },
        NvimTreeGitDeleted = { fg = colors.neutral_red },
        NvimTreeWindowPicker = { bg = colors.aqua },
        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "PantsboxRedSign" },
        StartifyBracket = { link = "PantsboxFg3" },
        StartifyFile = { link = "PantsboxFg1" },
        StartifyNumber = { link = "PantsboxBlue" },
        StartifyPath = { link = "PantsboxGray" },
        StartifySlash = { link = "PantsboxGray" },
        StartifySection = { link = "PantsboxYellow" },
        StartifySpecial = { link = "PantsboxBg2" },
        StartifyHeader = { link = "PantsboxOrange" },
        StartifyFooter = { link = "PantsboxBg2" },
        StartifyVar = { link = "StartifyPath" },
        StartifySelect = { link = "Title" },
        DirvishPathTail = { link = "PantsboxAqua" },
        DirvishArg = { link = "PantsboxYellow" },
        netrwDir = { link = "PantsboxAqua" },
        netrwClassify = { link = "PantsboxAqua" },
        netrwLink = { link = "PantsboxGray" },
        netrwSymLink = { link = "PantsboxFg1" },
        netrwExe = { link = "PantsboxYellow" },
        netrwComment = { link = "PantsboxGray" },
        netrwList = { link = "PantsboxBlue" },
        netrwHelpCmd = { link = "PantsboxAqua" },
        netrwCmdSep = { link = "PantsboxFg3" },
        netrwVersion = { link = "PantsboxGreen" },
        NERDTreeDir = { link = "PantsboxAqua" },
        NERDTreeDirSlash = { link = "PantsboxAqua" },
        NERDTreeOpenable = { link = "PantsboxOrange" },
        NERDTreeClosable = { link = "PantsboxOrange" },
        NERDTreeFile = { link = "PantsboxFg1" },
        NERDTreeExecFile = { link = "PantsboxYellow" },
        NERDTreeUp = { link = "PantsboxGray" },
        NERDTreeCWD = { link = "PantsboxGreen" },
        NERDTreeHelp = { link = "PantsboxFg1" },
        NERDTreeToggleOn = { link = "PantsboxGreen" },
        NERDTreeToggleOff = { link = "PantsboxRed" },
        CocErrorSign = { link = "PantsboxRedSign" },
        CocWarningSign = { link = "PantsboxOrangeSign" },
        CocInfoSign = { link = "PantsboxBlueSign" },
        CocHintSign = { link = "PantsboxAquaSign" },
        CocErrorFloat = { link = "PantsboxRed" },
        CocWarningFloat = { link = "PantsboxOrange" },
        CocInfoFloat = { link = "PantsboxBlue" },
        CocHintFloat = { link = "PantsboxAqua" },
        CocDiagnosticsError = { link = "PantsboxRed" },
        CocDiagnosticsWarning = { link = "PantsboxOrange" },
        CocDiagnosticsInfo = { link = "PantsboxBlue" },
        CocDiagnosticsHint = { link = "PantsboxAqua" },
        CocSelectedText = { link = "PantsboxRed" },
        CocMenuSel = { link = "PmenuSel" },
        CocCodeLens = { link = "PantsboxGray" },
        CocErrorHighlight = { link = "PantsboxRedUnderline" },
        CocWarningHighlight = { link = "PantsboxOrangeUnderline" },
        CocInfoHighlight = { link = "PantsboxBlueUnderline" },
        CocHintHighlight = { link = "PantsboxAquaUnderline" },
        TelescopeNormal = { link = "PantsboxFg1" },
        TelescopeSelection = { link = "PantsboxOrangeBold" },
        TelescopeSelectionCaret = { link = "PantsboxRed" },
        TelescopeMultiSelection = { link = "PantsboxGray" },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { link = "PantsboxBlue" },
        TelescopePromptPrefix = { link = "PantsboxRed" },
        TelescopePrompt = { link = "TelescopeNormal" },
        CmpItemAbbr = { link = "PantsboxFg0" },
        CmpItemAbbrDeprecated = { link = "PantsboxFg1" },
        CmpItemAbbrMatch = { link = "PantsboxBlueBold" },
        CmpItemAbbrMatchFuzzy = { link = "PantsboxBlueUnderline" },
        CmpItemMenu = { link = "PantsboxGray" },
        CmpItemKindText = { link = "PantsboxOrange" },
        CmpItemKindVariable = { link = "PantsboxOrange" },
        CmpItemKindMethod = { link = "PantsboxBlue" },
        CmpItemKindFunction = { link = "PantsboxBlue" },
        CmpItemKindConstructor = { link = "PantsboxYellow" },
        CmpItemKindUnit = { link = "PantsboxBlue" },
        CmpItemKindField = { link = "PantsboxBlue" },
        CmpItemKindClass = { link = "PantsboxYellow" },
        CmpItemKindInterface = { link = "PantsboxYellow" },
        CmpItemKindModule = { link = "PantsboxBlue" },
        CmpItemKindProperty = { link = "PantsboxBlue" },
        CmpItemKindValue = { link = "PantsboxOrange" },
        CmpItemKindEnum = { link = "PantsboxYellow" },
        CmpItemKindOperator = { link = "PantsboxYellow" },
        CmpItemKindKeyword = { link = "PantsboxPurple" },
        CmpItemKindEvent = { link = "PantsboxPurple" },
        CmpItemKindReference = { link = "PantsboxPurple" },
        CmpItemKindColor = { link = "PantsboxPurple" },
        CmpItemKindSnippet = { link = "PantsboxGreen" },
        CmpItemKindFile = { link = "PantsboxBlue" },
        CmpItemKindFolder = { link = "PantsboxBlue" },
        CmpItemKindEnumMember = { link = "PantsboxAqua" },
        CmpItemKindConstant = { link = "PantsboxOrange" },
        CmpItemKindStruct = { link = "PantsboxYellow" },
        CmpItemKindTypeParameter = { link = "PantsboxYellow" },
        diffAdded = { link = "DiffAdd" },
        diffRemoved = { link = "DiffDelete" },
        diffChanged = { link = "DiffChange" },
        diffFile = { link = "PantsboxOrange" },
        diffNewFile = { link = "PantsboxYellow" },
        diffOldFile = { link = "PantsboxOrange" },
        diffLine = { link = "PantsboxBlue" },
        diffIndexLine = { link = "diffChanged" },
        NavicIconsFile = { link = "PantsboxBlue" },
        NavicIconsModule = { link = "PantsboxOrange" },
        NavicIconsNamespace = { link = "PantsboxBlue" },
        NavicIconsPackage = { link = "PantsboxAqua" },
        NavicIconsClass = { link = "PantsboxYellow" },
        NavicIconsMethod = { link = "PantsboxBlue" },
        NavicIconsProperty = { link = "PantsboxAqua" },
        NavicIconsField = { link = "PantsboxPurple" },
        NavicIconsConstructor = { link = "PantsboxBlue" },
        NavicIconsEnum = { link = "PantsboxPurple" },
        NavicIconsInterface = { link = "PantsboxGreen" },
        NavicIconsFunction = { link = "PantsboxBlue" },
        NavicIconsVariable = { link = "PantsboxPurple" },
        NavicIconsConstant = { link = "PantsboxOrange" },
        NavicIconsString = { link = "PantsboxGreen" },
        NavicIconsNumber = { link = "PantsboxOrange" },
        NavicIconsBoolean = { link = "PantsboxOrange" },
        NavicIconsArray = { link = "PantsboxOrange" },
        NavicIconsObject = { link = "PantsboxOrange" },
        NavicIconsKey = { link = "PantsboxAqua" },
        NavicIconsNull = { link = "PantsboxOrange" },
        NavicIconsEnumMember = { link = "PantsboxYellow" },
        NavicIconsStruct = { link = "PantsboxPurple" },
        NavicIconsEvent = { link = "PantsboxYellow" },
        NavicIconsOperator = { link = "PantsboxRed" },
        NavicIconsTypeParameter = { link = "PantsboxRed" },
        NavicText = { link = "PantsboxWhite" },
        NavicSeparator = { link = "PantsboxWhite" },
        htmlTag = { link = "PantsboxAquaBold" },
        htmlEndTag = { link = "PantsboxAquaBold" },
        htmlTagName = { link = "PantsboxBlue" },
        htmlArg = { link = "PantsboxOrange" },
        htmlTagN = { link = "PantsboxFg1" },
        htmlSpecialTagName = { link = "PantsboxBlue" },
        htmlLink = { fg = colors.fg4, underline = config.underline },
        htmlSpecialChar = { link = "PantsboxRed" },
        htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
        htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
        htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
        htmlBoldUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            bold = config.bold,
            italic = true,
            underline = config.underline,
        },
        htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
        htmlUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            italic = true,
            underline = config.underline,
        },
        htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
        xmlTag = { link = "PantsboxAquaBold" },
        xmlEndTag = { link = "PantsboxAquaBold" },
        xmlTagName = { link = "PantsboxBlue" },
        xmlEqual = { link = "PantsboxBlue" },
        docbkKeyword = { link = "PantsboxAquaBold" },
        xmlDocTypeDecl = { link = "PantsboxGray" },
        xmlDocTypeKeyword = { link = "PantsboxPurple" },
        xmlCdataStart = { link = "PantsboxGray" },
        xmlCdataCdata = { link = "PantsboxPurple" },
        dtdFunction = { link = "PantsboxGray" },
        dtdTagName = { link = "PantsboxPurple" },
        xmlAttrib = { link = "PantsboxOrange" },
        xmlProcessingDelim = { link = "PantsboxGray" },
        dtdParamEntityPunct = { link = "PantsboxGray" },
        dtdParamEntityDPunct = { link = "PantsboxGray" },
        xmlAttribPunct = { link = "PantsboxGray" },
        xmlEntity = { link = "PantsboxRed" },
        xmlEntityPunct = { link = "PantsboxRed" },
        clojureKeyword = { link = "PantsboxBlue" },
        clojureCond = { link = "PantsboxOrange" },
        clojureSpecial = { link = "PantsboxOrange" },
        clojureDefine = { link = "PantsboxOrange" },
        clojureFunc = { link = "PantsboxYellow" },
        clojureRepeat = { link = "PantsboxYellow" },
        clojureCharacter = { link = "PantsboxAqua" },
        clojureStringEscape = { link = "PantsboxAqua" },
        clojureException = { link = "PantsboxRed" },
        clojureRegexp = { link = "PantsboxAqua" },
        clojureRegexpEscape = { link = "PantsboxAqua" },
        clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
        clojureRegexpMod = { link = "clojureRegexpCharClass" },
        clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
        clojureParen = { link = "PantsboxFg3" },
        clojureAnonArg = { link = "PantsboxYellow" },
        clojureVariable = { link = "PantsboxBlue" },
        clojureMacro = { link = "PantsboxOrange" },
        clojureMeta = { link = "PantsboxYellow" },
        clojureDeref = { link = "PantsboxYellow" },
        clojureQuote = { link = "PantsboxYellow" },
        clojureUnquote = { link = "PantsboxYellow" },
        cOperator = { link = "PantsboxPurple" },
        cppOperator = { link = "PantsboxPurple" },
        cStructure = { link = "PantsboxOrange" },
        pythonBuiltin = { link = "PantsboxOrange" },
        pythonBuiltinObj = { link = "PantsboxOrange" },
        pythonBuiltinFunc = { link = "PantsboxOrange" },
        pythonFunction = { link = "PantsboxAqua" },
        pythonDecorator = { link = "PantsboxRed" },
        pythonInclude = { link = "PantsboxBlue" },
        pythonImport = { link = "PantsboxBlue" },
        pythonRun = { link = "PantsboxBlue" },
        pythonCoding = { link = "PantsboxBlue" },
        pythonOperator = { link = "PantsboxRed" },
        pythonException = { link = "PantsboxRed" },
        pythonExceptions = { link = "PantsboxPurple" },
        pythonBoolean = { link = "PantsboxPurple" },
        pythonDot = { link = "PantsboxFg3" },
        pythonConditional = { link = "PantsboxRed" },
        pythonRepeat = { link = "PantsboxRed" },
        pythonDottedName = { link = "PantsboxGreenBold" },
        cssBraces = { link = "PantsboxBlue" },
        cssFunctionName = { link = "PantsboxYellow" },
        cssIdentifier = { link = "PantsboxOrange" },
        cssClassName = { link = "PantsboxGreen" },
        cssColor = { link = "PantsboxBlue" },
        cssSelectorOp = { link = "PantsboxBlue" },
        cssSelectorOp2 = { link = "PantsboxBlue" },
        cssImportant = { link = "PantsboxGreen" },
        cssVendor = { link = "PantsboxFg1" },
        cssTextProp = { link = "PantsboxAqua" },
        cssAnimationProp = { link = "PantsboxAqua" },
        cssUIProp = { link = "PantsboxYellow" },
        cssTransformProp = { link = "PantsboxAqua" },
        cssTransitionProp = { link = "PantsboxAqua" },
        cssPrintProp = { link = "PantsboxAqua" },
        cssPositioningProp = { link = "PantsboxYellow" },
        cssBoxProp = { link = "PantsboxAqua" },
        cssFontDescriptorProp = { link = "PantsboxAqua" },
        cssFlexibleBoxProp = { link = "PantsboxAqua" },
        cssBorderOutlineProp = { link = "PantsboxAqua" },
        cssBackgroundProp = { link = "PantsboxAqua" },
        cssMarginProp = { link = "PantsboxAqua" },
        cssListProp = { link = "PantsboxAqua" },
        cssTableProp = { link = "PantsboxAqua" },
        cssFontProp = { link = "PantsboxAqua" },
        cssPaddingProp = { link = "PantsboxAqua" },
        cssDimensionProp = { link = "PantsboxAqua" },
        cssRenderProp = { link = "PantsboxAqua" },
        cssColorProp = { link = "PantsboxAqua" },
        cssGeneratedContentProp = { link = "PantsboxAqua" },
        javaScriptBraces = { link = "PantsboxFg1" },
        javaScriptFunction = { link = "PantsboxAqua" },
        javaScriptIdentifier = { link = "PantsboxRed" },
        javaScriptMember = { link = "PantsboxBlue" },
        javaScriptNumber = { link = "PantsboxPurple" },
        javaScriptNull = { link = "PantsboxPurple" },
        javaScriptParens = { link = "PantsboxFg3" },
        typescriptReserved = { link = "PantsboxAqua" },
        typescriptLabel = { link = "PantsboxAqua" },
        typescriptFuncKeyword = { link = "PantsboxAqua" },
        typescriptIdentifier = { link = "PantsboxOrange" },
        typescriptBraces = { link = "PantsboxFg1" },
        typescriptEndColons = { link = "PantsboxFg1" },
        typescriptDOMObjects = { link = "PantsboxFg1" },
        typescriptAjaxMethods = { link = "PantsboxFg1" },
        typescriptLogicSymbols = { link = "PantsboxFg1" },
        typescriptDocSeeTag = { link = "Comment" },
        typescriptDocParam = { link = "Comment" },
        typescriptDocTags = { link = "vimCommentTitle" },
        typescriptGlobalObjects = { link = "PantsboxFg1" },
        typescriptParens = { link = "PantsboxFg3" },
        typescriptOpSymbols = { link = "PantsboxFg3" },
        typescriptHtmlElemProperties = { link = "PantsboxFg1" },
        typescriptNull = { link = "PantsboxPurple" },
        typescriptInterpolationDelimiter = { link = "PantsboxAqua" },
        purescriptModuleKeyword = { link = "PantsboxAqua" },
        purescriptModuleName = { link = "PantsboxFg1" },
        purescriptWhere = { link = "PantsboxAqua" },
        purescriptDelimiter = { link = "PantsboxFg4" },
        purescriptType = { link = "PantsboxFg1" },
        purescriptImportKeyword = { link = "PantsboxAqua" },
        purescriptHidingKeyword = { link = "PantsboxAqua" },
        purescriptAsKeyword = { link = "PantsboxAqua" },
        purescriptStructure = { link = "PantsboxAqua" },
        purescriptOperator = { link = "PantsboxBlue" },
        purescriptTypeVar = { link = "PantsboxFg1" },
        purescriptConstructor = { link = "PantsboxFg1" },
        purescriptFunction = { link = "PantsboxFg1" },
        purescriptConditional = { link = "PantsboxOrange" },
        purescriptBacktick = { link = "PantsboxOrange" },
        coffeeExtendedOp = { link = "PantsboxFg3" },
        coffeeSpecialOp = { link = "PantsboxFg3" },
        coffeeCurly = { link = "PantsboxOrange" },
        coffeeParen = { link = "PantsboxFg3" },
        coffeeBracket = { link = "PantsboxOrange" },
        rubyStringDelimiter = { link = "PantsboxGreen" },
        rubyInterpolationDelimiter = { link = "PantsboxAqua" },
        rubyDefinedOperator = { link = "rubyKeyword" },
        objcTypeModifier = { link = "PantsboxRed" },
        objcDirective = { link = "PantsboxBlue" },
        goDirective = { link = "PantsboxAqua" },
        goConstants = { link = "PantsboxPurple" },
        goDeclaration = { link = "PantsboxRed" },
        goDeclType = { link = "PantsboxBlue" },
        goBuiltins = { link = "PantsboxOrange" },
        luaIn = { link = "PantsboxRed" },
        luaFunction = { link = "PantsboxAqua" },
        luaTable = { link = "PantsboxOrange" },
        moonSpecialOp = { link = "PantsboxFg3" },
        moonExtendedOp = { link = "PantsboxFg3" },
        moonFunction = { link = "PantsboxFg3" },
        moonObject = { link = "PantsboxYellow" },
        javaAnnotation = { link = "PantsboxBlue" },
        javaDocTags = { link = "PantsboxAqua" },
        javaCommentTitle = { link = "vimCommentTitle" },
        javaParen = { link = "PantsboxFg3" },
        javaParen1 = { link = "PantsboxFg3" },
        javaParen2 = { link = "PantsboxFg3" },
        javaParen3 = { link = "PantsboxFg3" },
        javaParen4 = { link = "PantsboxFg3" },
        javaParen5 = { link = "PantsboxFg3" },
        javaOperator = { link = "PantsboxOrange" },
        javaVarArg = { link = "PantsboxGreen" },
        elixirDocString = { link = "Comment" },
        elixirStringDelimiter = { link = "PantsboxGreen" },
        elixirInterpolationDelimiter = { link = "PantsboxAqua" },
        elixirModuleDeclaration = { link = "PantsboxYellow" },
        scalaNameDefinition = { link = "PantsboxFg1" },
        scalaCaseFollowing = { link = "PantsboxFg1" },
        scalaCapitalWord = { link = "PantsboxFg1" },
        scalaTypeExtension = { link = "PantsboxFg1" },
        scalaKeyword = { link = "PantsboxRed" },
        scalaKeywordModifier = { link = "PantsboxRed" },
        scalaSpecial = { link = "PantsboxAqua" },
        scalaOperator = { link = "PantsboxFg1" },
        scalaTypeDeclaration = { link = "PantsboxYellow" },
        scalaTypeTypePostDeclaration = { link = "PantsboxYellow" },
        scalaInstanceDeclaration = { link = "PantsboxFg1" },
        scalaInterpolation = { link = "PantsboxAqua" },
        markdownItalic = { fg = colors.fg3, italic = true },
        markdownBold = { fg = colors.fg3, bold = config.bold },
        markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
        markdownH1 = { link = "PantsboxGreenBold" },
        markdownH2 = { link = "PantsboxGreenBold" },
        markdownH3 = { link = "PantsboxYellowBold" },
        markdownH4 = { link = "PantsboxYellowBold" },
        markdownH5 = { link = "PantsboxYellow" },
        markdownH6 = { link = "PantsboxYellow" },
        markdownCode = { link = "PantsboxAqua" },
        markdownCodeBlock = { link = "PantsboxAqua" },
        markdownCodeDelimiter = { link = "PantsboxAqua" },
        markdownBlockquote = { link = "PantsboxGray" },
        markdownListMarker = { link = "PantsboxGray" },
        markdownOrderedListMarker = { link = "PantsboxGray" },
        markdownRule = { link = "PantsboxGray" },
        markdownHeadingRule = { link = "PantsboxGray" },
        markdownUrlDelimiter = { link = "PantsboxFg3" },
        markdownLinkDelimiter = { link = "PantsboxFg3" },
        markdownLinkTextDelimiter = { link = "PantsboxFg3" },
        markdownHeadingDelimiter = { link = "PantsboxOrange" },
        markdownUrl = { link = "PantsboxPurple" },
        markdownUrlTitleDelimiter = { link = "PantsboxGreen" },
        markdownLinkText = { fg = colors.gray, underline = config.underline },
        markdownIdDeclaration = { link = "markdownLinkText" },
        haskellType = { link = "PantsboxBlue" },
        haskellIdentifier = { link = "PantsboxAqua" },
        haskellSeparator = { link = "PantsboxFg4" },
        haskellDelimiter = { link = "PantsboxOrange" },
        haskellOperators = { link = "PantsboxPurple" },
        haskellBacktick = { link = "PantsboxOrange" },
        haskellStatement = { link = "PantsboxPurple" },
        haskellConditional = { link = "PantsboxPurple" },
        haskellLet = { link = "PantsboxRed" },
        haskellDefault = { link = "PantsboxRed" },
        haskellWhere = { link = "PantsboxRed" },
        haskellBottom = { link = "PantsboxRedBold" },
        haskellImportKeywords = { link = "PantsboxPurpleBold" },
        haskellDeclKeyword = { link = "PantsboxOrange" },
        haskellDecl = { link = "PantsboxOrange" },
        haskellDeriving = { link = "PantsboxPurple" },
        haskellAssocType = { link = "PantsboxAqua" },
        haskellNumber = { link = "PantsboxAqua" },
        haskellPragma = { link = "PantsboxRedBold" },
        haskellTH = { link = "PantsboxAquaBold" },
        haskellForeignKeywords = { link = "PantsboxGreen" },
        haskellKeyword = { link = "PantsboxRed" },
        haskellFloat = { link = "PantsboxAqua" },
        haskellInfix = { link = "PantsboxPurple" },
        haskellQuote = { link = "PantsboxGreenBold" },
        haskellShebang = { link = "PantsboxYellowBold" },
        haskellLiquid = { link = "PantsboxPurpleBold" },
        haskellQuasiQuoted = { link = "PantsboxBlueBold" },
        haskellRecursiveDo = { link = "PantsboxPurple" },
        haskellQuotedType = { link = "PantsboxRed" },
        haskellPreProc = { link = "PantsboxFg4" },
        haskellTypeRoles = { link = "PantsboxRedBold" },
        haskellTypeForall = { link = "PantsboxRed" },
        haskellPatternKeyword = { link = "PantsboxBlue" },
        jsonKeyword = { link = "PantsboxGreen" },
        jsonQuote = { link = "PantsboxGreen" },
        jsonBraces = { link = "PantsboxFg1" },
        jsonString = { link = "PantsboxFg1" },
        mailQuoted1 = { link = "PantsboxAqua" },
        mailQuoted2 = { link = "PantsboxPurple" },
        mailQuoted3 = { link = "PantsboxYellow" },
        mailQuoted4 = { link = "PantsboxGreen" },
        mailQuoted5 = { link = "PantsboxRed" },
        mailQuoted6 = { link = "PantsboxOrange" },
        mailSignature = { link = "Comment" },
        csBraces = { link = "PantsboxFg1" },
        csEndColon = { link = "PantsboxFg1" },
        csLogicSymbols = { link = "PantsboxFg1" },
        csParens = { link = "PantsboxFg3" },
        csOpSymbols = { link = "PantsboxFg3" },
        csInterpolationDelimiter = { link = "PantsboxFg3" },
        csInterpolationAlignDel = { link = "PantsboxAquaBold" },
        csInterpolationFormat = { link = "PantsboxAqua" },
        csInterpolationFormatDel = { link = "PantsboxAquaBold" },
        rustSigil = { link = "PantsboxOrange" },
        rustEscape = { link = "PantsboxAqua" },
        rustStringContinuation = { link = "PantsboxAqua" },
        rustEnum = { link = "PantsboxAqua" },
        rustStructure = { link = "PantsboxAqua" },
        rustModPathSep = { link = "PantsboxFg2" },
        rustCommentLineDoc = { link = "Comment" },
        rustDefault = { link = "PantsboxAqua" },
        ocamlOperator = { link = "PantsboxFg1" },
        ocamlKeyChar = { link = "PantsboxOrange" },
        ocamlArrow = { link = "PantsboxOrange" },
        ocamlInfixOpKeyword = { link = "PantsboxRed" },
        ocamlConstructor = { link = "PantsboxOrange" },
        LspSagaCodeActionTitle = { link = "Title" },
        LspSagaCodeActionBorder = { link = "PantsboxFg1" },
        LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
        LspSagaLspFinderBorder = { link = "PantsboxFg1" },
        LspSagaAutoPreview = { link = "PantsboxOrange" },
        TargetWord = { fg = colors.blue, bold = config.bold },
        FinderSeparator = { link = "PantsboxAqua" },
        LspSagaDefPreviewBorder = { link = "PantsboxBlue" },
        LspSagaHoverBorder = { link = "PantsboxOrange" },
        LspSagaRenameBorder = { link = "PantsboxBlue" },
        LspSagaDiagnosticSource = { link = "PantsboxOrange" },
        LspSagaDiagnosticBorder = { link = "PantsboxPurple" },
        LspSagaDiagnosticHeader = { link = "PantsboxGreen" },
        LspSagaSignatureHelpBorder = { link = "PantsboxGreen" },
        SagaShadow = { link = "PantsboxBg0" },
        DashboardShortCut = { link = "PantsboxOrange" },
        DashboardHeader = { link = "PantsboxAqua" },
        DashboardCenter = { link = "PantsboxYellow" },
        DashboardFooter = { fg = colors.purple, italic = true },
        MasonHighlight = { link = "PantsboxAqua" },
        MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
        MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
        MasonHighlightSecondary = { fg = colors.yellow },
        MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
        MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
        MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
        MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
        MasonMuted = { fg = colors.fg4 },
        MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
        MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
        LspInlayHint = { link = "comment" },
        CarbonFile = { link = "PantsboxFg1" },
        CarbonExe = { link = "PantsboxYellow" },
        CarbonSymlink = { link = "PantsboxAqua" },
        CarbonBrokenSymlink = { link = "PantsboxRed" },
        CarbonIndicator = { link = "PantsboxGray" },
        CarbonDanger = { link = "PantsboxRed" },
        CarbonPending = { link = "PantsboxYellow" },
        NoiceCursor = { link = "TermCursor" },
        NotifyDEBUGBorder = { link = "PantsboxBlue" },
        NotifyDEBUGIcon = { link = "PantsboxBlue" },
        NotifyDEBUGTitle = { link = "PantsboxBlue" },
        NotifyERRORBorder = { link = "PantsboxRed" },
        NotifyERRORIcon = { link = "PantsboxRed" },
        NotifyERRORTitle = { link = "PantsboxRed" },
        NotifyINFOBorder = { link = "PantsboxAqua" },
        NotifyINFOIcon = { link = "PantsboxAqua" },
        NotifyINFOTitle = { link = "PantsboxAqua" },
        NotifyTRACEBorder = { link = "PantsboxGreen" },
        NotifyTRACEIcon = { link = "PantsboxGreen" },
        NotifyTRACETitle = { link = "PantsboxGreen" },
        NotifyWARNBorder = { link = "PantsboxYellow" },
        NotifyWARNIcon = { link = "PantsboxYellow" },
        NotifyWARNTitle = { link = "PantsboxYellow" },
        IlluminatedWordText = { link = "LspReferenceText" },
        IlluminatedWordRead = { link = "LspReferenceRead" },
        IlluminatedWordWrite = { link = "LspReferenceWrite" },
        TSRainbowRed = { fg = colors.red },
        TSRainbowOrange = { fg = colors.orange },
        TSRainbowYellow = { fg = colors.yellow },
        TSRainbowGreen = { fg = colors.green },
        TSRainbowBlue = { fg = colors.blue },
        TSRainbowViolet = { fg = colors.purple },
        TSRainbowCyan = { fg = colors.cyan },
        DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
        DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
        DapUIBreakpointsCurrentLine = { link = "PantsboxYellow" },
        DapUIBreakpointsDisabledLine = { link = "PantsboxGray" },
        DapUIBreakpointsInfo = { link = "PantsboxAqua" },
        DapUIBreakpointsLine = { link = "PantsboxYellow" },
        DapUIBreakpointsPath = { link = "PantsboxBlue" },
        DapUICurrentFrameName = { link = "PantsboxPurple" },
        DapUIDecoration = { link = "PantsboxPurple" },
        DapUIEndofBuffer = { link = "PantsboxBg2" },
        DapUIFloatBorder = { link = "PantsboxAqua" },
        DapUILineNumber = { link = "PantsboxYellow" },
        DapUIModifiedValue = { link = "PantsboxRed" },
        DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
        DapUIRestart = { fg = colors.green, bg = colors.bg1 },
        DapUIScope = { link = "PantsboxBlue" },
        DapUISource = { link = "PantsboxFg1" },
        DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
        DapUIStop = { fg = colors.red, bg = colors.bg1 },
        DapUIStoppedThread = { link = "PantsboxBlue" },
        DapUIThread = { link = "PantsboxBlue" },
        DapUIType = { link = "PantsboxOrange" },
        DapUIUnavailable = { link = "PantsboxGray" },
        DapUIWatchesEmpty = { link = "PantsboxGray" },
        DapUIWatchesError = { link = "PantsboxRed" },
        DapUIWatchesValue = { link = "PantsboxYellow" },
        DapUIWinSelect = { link = "PantsboxYellow" },
        NeogitDiffDelete = { link = "DiffDelete" },
        NeogitDiffAdd = { link = "DiffAdd" },
        NeogitHunkHeader = { link = "WinBar" },
        NeogitHunkHeaderHighlight = { link = "WinBarNC" },
        DiffviewStatusModified = { link = "PantsboxGreenBold" },
        DiffviewFilePanelInsertions = { link = "PantsboxGreenBold" },
        DiffviewFilePanelDeletions = { link = "PantsboxRedBold" },
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { link = "PantsboxRed" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "PantsboxFg1" },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@markup"] = { link = "PantsboxFg1" },
        ["@markup.strong"] = { bold = config.bold },
        ["@markup.emphasis"] = { italic = config.italic.emphasis },
        ["@markup.underline"] = { underline = config.underline },
        ["@markup.strike"] = { strikethrough = config.strikethrough },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.math"] = { link = "Special" },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { link = "Type" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { link = "PantsboxGreen" },
        ["@markup.list.unchecked"] = { link = "PantsboxGray" },
        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "SpecialComment" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },
        ["@diff.plus"] = { link = "diffAdded" },
        ["@diff.minus"] = { link = "diffRemoved" },
        ["@diff.delta"] = { link = "diffChanged" },
        ["@module"] = { link = "PantsboxFg1" },
        ["@namespace"] = { link = "PantsboxFg1" },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { link = "PantsboxFg1" },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { link = "PantsboxGreen" },
        ["@text.todo.unchecked"] = { link = "PantsboxGray" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
        ["@text.diff.add"] = { link = "diffAdded" },
        ["@text.diff.delete"] = { link = "diffRemoved" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },
    }

    for group, hl in pairs(config.overrides) do
        if groups[group] then
            -- "link" should not mix with other configs (:h hi-link)
            groups[group].link = nil
        end

        groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
    end

    return groups
end

---@param config PantsboxConfig?
Pantsbox.setup = function(config)
    Pantsbox.config = vim.tbl_deep_extend("force", Pantsbox.config, config or {})
end

--- main load function
Pantsbox.load = function()
    if vim.version().minor < 8 then
        vim.notify_once("pantsbox.nvim: you must use neovim 0.8 or higher")
        return
    end

    -- reset colors
    if vim.g.colors_name then
        vim.cmd.hi("clear")
    end
    vim.g.colors_name = "pantsbox"
    vim.o.termguicolors = true

    local groups = get_groups()

    -- add highlights
    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

return Pantsbox
